package com.ssm.dao;

import com.ssm.pojo.TbEmployee;
import com.ssm.pojo.TbEmployeeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    long countByExample(TbEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int deleteByExample(TbEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int insert(TbEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int insertSelective(TbEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    List<TbEmployee> selectByExample(TbEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    TbEmployee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExampleSelective(@Param("record") TbEmployee record, @Param("example") TbEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExample(@Param("record") TbEmployee record, @Param("example") TbEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKeySelective(TbEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKey(TbEmployee record);
}