package com.ssm.dao;

import com.ssm.pojo.TbInvitejob;
import com.ssm.pojo.TbInvitejobExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbInvitejobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    long countByExample(TbInvitejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int deleteByExample(TbInvitejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int insert(TbInvitejob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int insertSelective(TbInvitejob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    List<TbInvitejob> selectByExampleWithBLOBs(TbInvitejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    List<TbInvitejob> selectByExample(TbInvitejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    TbInvitejob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int updateByExampleSelective(@Param("record") TbInvitejob record, @Param("example") TbInvitejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TbInvitejob record, @Param("example") TbInvitejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int updateByExample(@Param("record") TbInvitejob record, @Param("example") TbInvitejobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int updateByPrimaryKeySelective(TbInvitejob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int updateByPrimaryKeyWithBLOBs(TbInvitejob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_invitejob
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    int updateByPrimaryKey(TbInvitejob record);
}