package com.ssm.dao;

import com.ssm.pojo.TbManager;
import com.ssm.pojo.TbManagerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    long countByExample(TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int deleteByExample(TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int insert(TbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int insertSelective(TbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    List<TbManager> selectByExample(TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    TbManager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExampleSelective(@Param("record") TbManager record, @Param("example") TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExample(@Param("record") TbManager record, @Param("example") TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKeySelective(TbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKey(TbManager record);
}