package com.ssm.dao;

import com.ssm.pojo.TbPay;
import com.ssm.pojo.TbPayExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    long countByExample(TbPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int deleteByExample(TbPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int insert(TbPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int insertSelective(TbPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    List<TbPay> selectByExample(TbPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    TbPay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExampleSelective(@Param("record") TbPay record, @Param("example") TbPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExample(@Param("record") TbPay record, @Param("example") TbPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKeySelective(TbPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKey(TbPay record);
}