package com.ssm.dao;

import com.ssm.pojo.TbTrain;
import com.ssm.pojo.TbTrainExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbTrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    long countByExample(TbTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int deleteByExample(TbTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int insert(TbTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int insertSelective(TbTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    List<TbTrain> selectByExampleWithBLOBs(TbTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    List<TbTrain> selectByExample(TbTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    TbTrain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExampleSelective(@Param("record") TbTrain record, @Param("example") TbTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TbTrain record, @Param("example") TbTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByExample(@Param("record") TbTrain record, @Param("example") TbTrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKeySelective(TbTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKeyWithBLOBs(TbTrain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_train
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    int updateByPrimaryKey(TbTrain record);
}