package com.ssm.pojo;

import java.util.Date;

public class TbDepartment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.id
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.dt_name
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private String dtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.dt_createTime
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Date dtCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_department.dt_responsibility
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private String dtResponsibility;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.id
     *
     * @return the value of tb_department.id
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.id
     *
     * @param id the value for tb_department.id
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.dt_name
     *
     * @return the value of tb_department.dt_name
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public String getDtName() {
        return dtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.dt_name
     *
     * @param dtName the value for tb_department.dt_name
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setDtName(String dtName) {
        this.dtName = dtName == null ? null : dtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.dt_createTime
     *
     * @return the value of tb_department.dt_createTime
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Date getDtCreatetime() {
        return dtCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.dt_createTime
     *
     * @param dtCreatetime the value for tb_department.dt_createTime
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setDtCreatetime(Date dtCreatetime) {
        this.dtCreatetime = dtCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_department.dt_responsibility
     *
     * @return the value of tb_department.dt_responsibility
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public String getDtResponsibility() {
        return dtResponsibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_department.dt_responsibility
     *
     * @param dtResponsibility the value for tb_department.dt_responsibility
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setDtResponsibility(String dtResponsibility) {
        this.dtResponsibility = dtResponsibility == null ? null : dtResponsibility.trim();
    }
}