package com.ssm.pojo;

import com.fasterxml.jackson.annotation.JsonView;
import com.ssm.pojo.custompojo.Invitejob;

import java.util.Date;

public class TbInvitejob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.id
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.firstname
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.lastname
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.sex
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.age
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.born
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String born;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.job
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.specialty
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String specialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.experience
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.teachSchool
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String teachschool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.afterSchool
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String afterschool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.tel
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.address
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.createtime
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.DetailsView.class)
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.isstock
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private Integer isstock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_invitejob.content
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    @JsonView(Invitejob.Views.QueryView.class)
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.id
     *
     * @return the value of tb_invitejob.id
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.id
     *
     * @param id the value for tb_invitejob.id
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.firstname
     *
     * @return the value of tb_invitejob.firstname
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.firstname
     *
     * @param firstname the value for tb_invitejob.firstname
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.lastname
     *
     * @return the value of tb_invitejob.lastname
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.lastname
     *
     * @param lastname the value for tb_invitejob.lastname
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.sex
     *
     * @return the value of tb_invitejob.sex
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.sex
     *
     * @param sex the value for tb_invitejob.sex
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.age
     *
     * @return the value of tb_invitejob.age
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.age
     *
     * @param age the value for tb_invitejob.age
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.born
     *
     * @return the value of tb_invitejob.born
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getBorn() {
        return born;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.born
     *
     * @param born the value for tb_invitejob.born
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setBorn(String born) {
        this.born = born == null ? null : born.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.job
     *
     * @return the value of tb_invitejob.job
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.job
     *
     * @param job the value for tb_invitejob.job
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.specialty
     *
     * @return the value of tb_invitejob.specialty
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.specialty
     *
     * @param specialty the value for tb_invitejob.specialty
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty == null ? null : specialty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.experience
     *
     * @return the value of tb_invitejob.experience
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.experience
     *
     * @param experience the value for tb_invitejob.experience
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.teachSchool
     *
     * @return the value of tb_invitejob.teachSchool
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getTeachschool() {
        return teachschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.teachSchool
     *
     * @param teachschool the value for tb_invitejob.teachSchool
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setTeachschool(String teachschool) {
        this.teachschool = teachschool == null ? null : teachschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.afterSchool
     *
     * @return the value of tb_invitejob.afterSchool
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getAfterschool() {
        return afterschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.afterSchool
     *
     * @param afterschool the value for tb_invitejob.afterSchool
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setAfterschool(String afterschool) {
        this.afterschool = afterschool == null ? null : afterschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.tel
     *
     * @return the value of tb_invitejob.tel
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.tel
     *
     * @param tel the value for tb_invitejob.tel
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.address
     *
     * @return the value of tb_invitejob.address
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.address
     *
     * @param address the value for tb_invitejob.address
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.createtime
     *
     * @return the value of tb_invitejob.createtime
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.createtime
     *
     * @param createtime the value for tb_invitejob.createtime
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.isstock
     *
     * @return the value of tb_invitejob.isstock
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public Integer getIsstock() {
        return isstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.isstock
     *
     * @param isstock the value for tb_invitejob.isstock
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setIsstock(Integer isstock) {
        this.isstock = isstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_invitejob.content
     *
     * @return the value of tb_invitejob.content
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_invitejob.content
     *
     * @param content the value for tb_invitejob.content
     *
     * @mbg.generated Sat Dec 22 13:36:31 AEDT 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}