package com.ssm.pojo;

import java.util.Date;

public class TbPay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.id
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_emNumber
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private String payEmnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_emName
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private String payEmname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_month
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Date payMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_baseMoney
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Integer payBasemoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_overtime
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Integer payOvertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_age
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Integer payAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_check
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Float payCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_absent
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Float payAbsent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pay.pay_safety
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    private Float paySafety;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.id
     *
     * @return the value of tb_pay.id
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.id
     *
     * @param id the value for tb_pay.id
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_emNumber
     *
     * @return the value of tb_pay.pay_emNumber
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public String getPayEmnumber() {
        return payEmnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_emNumber
     *
     * @param payEmnumber the value for tb_pay.pay_emNumber
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPayEmnumber(String payEmnumber) {
        this.payEmnumber = payEmnumber == null ? null : payEmnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_emName
     *
     * @return the value of tb_pay.pay_emName
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public String getPayEmname() {
        return payEmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_emName
     *
     * @param payEmname the value for tb_pay.pay_emName
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPayEmname(String payEmname) {
        this.payEmname = payEmname == null ? null : payEmname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_month
     *
     * @return the value of tb_pay.pay_month
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Date getPayMonth() {
        return payMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_month
     *
     * @param payMonth the value for tb_pay.pay_month
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPayMonth(Date payMonth) {
        this.payMonth = payMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_baseMoney
     *
     * @return the value of tb_pay.pay_baseMoney
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Integer getPayBasemoney() {
        return payBasemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_baseMoney
     *
     * @param payBasemoney the value for tb_pay.pay_baseMoney
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPayBasemoney(Integer payBasemoney) {
        this.payBasemoney = payBasemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_overtime
     *
     * @return the value of tb_pay.pay_overtime
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Integer getPayOvertime() {
        return payOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_overtime
     *
     * @param payOvertime the value for tb_pay.pay_overtime
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPayOvertime(Integer payOvertime) {
        this.payOvertime = payOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_age
     *
     * @return the value of tb_pay.pay_age
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Integer getPayAge() {
        return payAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_age
     *
     * @param payAge the value for tb_pay.pay_age
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPayAge(Integer payAge) {
        this.payAge = payAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_check
     *
     * @return the value of tb_pay.pay_check
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Float getPayCheck() {
        return payCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_check
     *
     * @param payCheck the value for tb_pay.pay_check
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPayCheck(Float payCheck) {
        this.payCheck = payCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_absent
     *
     * @return the value of tb_pay.pay_absent
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Float getPayAbsent() {
        return payAbsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_absent
     *
     * @param payAbsent the value for tb_pay.pay_absent
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPayAbsent(Float payAbsent) {
        this.payAbsent = payAbsent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pay.pay_safety
     *
     * @return the value of tb_pay.pay_safety
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Float getPaySafety() {
        return paySafety;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pay.pay_safety
     *
     * @param paySafety the value for tb_pay.pay_safety
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setPaySafety(Float paySafety) {
        this.paySafety = paySafety;
    }
}