package com.ssm.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TbPayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public TbPayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberIsNull() {
            addCriterion("pay_emNumber is null");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberIsNotNull() {
            addCriterion("pay_emNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberEqualTo(String value) {
            addCriterion("pay_emNumber =", value, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberNotEqualTo(String value) {
            addCriterion("pay_emNumber <>", value, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberGreaterThan(String value) {
            addCriterion("pay_emNumber >", value, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberGreaterThanOrEqualTo(String value) {
            addCriterion("pay_emNumber >=", value, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberLessThan(String value) {
            addCriterion("pay_emNumber <", value, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberLessThanOrEqualTo(String value) {
            addCriterion("pay_emNumber <=", value, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberLike(String value) {
            addCriterion("pay_emNumber like", value, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberNotLike(String value) {
            addCriterion("pay_emNumber not like", value, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberIn(List<String> values) {
            addCriterion("pay_emNumber in", values, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberNotIn(List<String> values) {
            addCriterion("pay_emNumber not in", values, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberBetween(String value1, String value2) {
            addCriterion("pay_emNumber between", value1, value2, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnumberNotBetween(String value1, String value2) {
            addCriterion("pay_emNumber not between", value1, value2, "payEmnumber");
            return (Criteria) this;
        }

        public Criteria andPayEmnameIsNull() {
            addCriterion("pay_emName is null");
            return (Criteria) this;
        }

        public Criteria andPayEmnameIsNotNull() {
            addCriterion("pay_emName is not null");
            return (Criteria) this;
        }

        public Criteria andPayEmnameEqualTo(String value) {
            addCriterion("pay_emName =", value, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameNotEqualTo(String value) {
            addCriterion("pay_emName <>", value, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameGreaterThan(String value) {
            addCriterion("pay_emName >", value, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameGreaterThanOrEqualTo(String value) {
            addCriterion("pay_emName >=", value, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameLessThan(String value) {
            addCriterion("pay_emName <", value, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameLessThanOrEqualTo(String value) {
            addCriterion("pay_emName <=", value, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameLike(String value) {
            addCriterion("pay_emName like", value, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameNotLike(String value) {
            addCriterion("pay_emName not like", value, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameIn(List<String> values) {
            addCriterion("pay_emName in", values, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameNotIn(List<String> values) {
            addCriterion("pay_emName not in", values, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameBetween(String value1, String value2) {
            addCriterion("pay_emName between", value1, value2, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayEmnameNotBetween(String value1, String value2) {
            addCriterion("pay_emName not between", value1, value2, "payEmname");
            return (Criteria) this;
        }

        public Criteria andPayMonthIsNull() {
            addCriterion("pay_month is null");
            return (Criteria) this;
        }

        public Criteria andPayMonthIsNotNull() {
            addCriterion("pay_month is not null");
            return (Criteria) this;
        }

        public Criteria andPayMonthEqualTo(Date value) {
            addCriterionForJDBCDate("pay_month =", value, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthNotEqualTo(Date value) {
            addCriterionForJDBCDate("pay_month <>", value, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthGreaterThan(Date value) {
            addCriterionForJDBCDate("pay_month >", value, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pay_month >=", value, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthLessThan(Date value) {
            addCriterionForJDBCDate("pay_month <", value, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pay_month <=", value, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthIn(List<Date> values) {
            addCriterionForJDBCDate("pay_month in", values, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthNotIn(List<Date> values) {
            addCriterionForJDBCDate("pay_month not in", values, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pay_month between", value1, value2, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayMonthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pay_month not between", value1, value2, "payMonth");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyIsNull() {
            addCriterion("pay_baseMoney is null");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyIsNotNull() {
            addCriterion("pay_baseMoney is not null");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyEqualTo(Integer value) {
            addCriterion("pay_baseMoney =", value, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyNotEqualTo(Integer value) {
            addCriterion("pay_baseMoney <>", value, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyGreaterThan(Integer value) {
            addCriterion("pay_baseMoney >", value, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_baseMoney >=", value, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyLessThan(Integer value) {
            addCriterion("pay_baseMoney <", value, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyLessThanOrEqualTo(Integer value) {
            addCriterion("pay_baseMoney <=", value, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyIn(List<Integer> values) {
            addCriterion("pay_baseMoney in", values, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyNotIn(List<Integer> values) {
            addCriterion("pay_baseMoney not in", values, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyBetween(Integer value1, Integer value2) {
            addCriterion("pay_baseMoney between", value1, value2, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayBasemoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_baseMoney not between", value1, value2, "payBasemoney");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeIsNull() {
            addCriterion("pay_overtime is null");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeIsNotNull() {
            addCriterion("pay_overtime is not null");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeEqualTo(Integer value) {
            addCriterion("pay_overtime =", value, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeNotEqualTo(Integer value) {
            addCriterion("pay_overtime <>", value, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeGreaterThan(Integer value) {
            addCriterion("pay_overtime >", value, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_overtime >=", value, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeLessThan(Integer value) {
            addCriterion("pay_overtime <", value, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_overtime <=", value, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeIn(List<Integer> values) {
            addCriterion("pay_overtime in", values, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeNotIn(List<Integer> values) {
            addCriterion("pay_overtime not in", values, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeBetween(Integer value1, Integer value2) {
            addCriterion("pay_overtime between", value1, value2, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayOvertimeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_overtime not between", value1, value2, "payOvertime");
            return (Criteria) this;
        }

        public Criteria andPayAgeIsNull() {
            addCriterion("pay_age is null");
            return (Criteria) this;
        }

        public Criteria andPayAgeIsNotNull() {
            addCriterion("pay_age is not null");
            return (Criteria) this;
        }

        public Criteria andPayAgeEqualTo(Integer value) {
            addCriterion("pay_age =", value, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeNotEqualTo(Integer value) {
            addCriterion("pay_age <>", value, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeGreaterThan(Integer value) {
            addCriterion("pay_age >", value, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_age >=", value, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeLessThan(Integer value) {
            addCriterion("pay_age <", value, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_age <=", value, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeIn(List<Integer> values) {
            addCriterion("pay_age in", values, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeNotIn(List<Integer> values) {
            addCriterion("pay_age not in", values, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeBetween(Integer value1, Integer value2) {
            addCriterion("pay_age between", value1, value2, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_age not between", value1, value2, "payAge");
            return (Criteria) this;
        }

        public Criteria andPayCheckIsNull() {
            addCriterion("pay_check is null");
            return (Criteria) this;
        }

        public Criteria andPayCheckIsNotNull() {
            addCriterion("pay_check is not null");
            return (Criteria) this;
        }

        public Criteria andPayCheckEqualTo(Float value) {
            addCriterion("pay_check =", value, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckNotEqualTo(Float value) {
            addCriterion("pay_check <>", value, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckGreaterThan(Float value) {
            addCriterion("pay_check >", value, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckGreaterThanOrEqualTo(Float value) {
            addCriterion("pay_check >=", value, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckLessThan(Float value) {
            addCriterion("pay_check <", value, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckLessThanOrEqualTo(Float value) {
            addCriterion("pay_check <=", value, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckIn(List<Float> values) {
            addCriterion("pay_check in", values, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckNotIn(List<Float> values) {
            addCriterion("pay_check not in", values, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckBetween(Float value1, Float value2) {
            addCriterion("pay_check between", value1, value2, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayCheckNotBetween(Float value1, Float value2) {
            addCriterion("pay_check not between", value1, value2, "payCheck");
            return (Criteria) this;
        }

        public Criteria andPayAbsentIsNull() {
            addCriterion("pay_absent is null");
            return (Criteria) this;
        }

        public Criteria andPayAbsentIsNotNull() {
            addCriterion("pay_absent is not null");
            return (Criteria) this;
        }

        public Criteria andPayAbsentEqualTo(Float value) {
            addCriterion("pay_absent =", value, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentNotEqualTo(Float value) {
            addCriterion("pay_absent <>", value, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentGreaterThan(Float value) {
            addCriterion("pay_absent >", value, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentGreaterThanOrEqualTo(Float value) {
            addCriterion("pay_absent >=", value, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentLessThan(Float value) {
            addCriterion("pay_absent <", value, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentLessThanOrEqualTo(Float value) {
            addCriterion("pay_absent <=", value, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentIn(List<Float> values) {
            addCriterion("pay_absent in", values, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentNotIn(List<Float> values) {
            addCriterion("pay_absent not in", values, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentBetween(Float value1, Float value2) {
            addCriterion("pay_absent between", value1, value2, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPayAbsentNotBetween(Float value1, Float value2) {
            addCriterion("pay_absent not between", value1, value2, "payAbsent");
            return (Criteria) this;
        }

        public Criteria andPaySafetyIsNull() {
            addCriterion("pay_safety is null");
            return (Criteria) this;
        }

        public Criteria andPaySafetyIsNotNull() {
            addCriterion("pay_safety is not null");
            return (Criteria) this;
        }

        public Criteria andPaySafetyEqualTo(Float value) {
            addCriterion("pay_safety =", value, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyNotEqualTo(Float value) {
            addCriterion("pay_safety <>", value, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyGreaterThan(Float value) {
            addCriterion("pay_safety >", value, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyGreaterThanOrEqualTo(Float value) {
            addCriterion("pay_safety >=", value, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyLessThan(Float value) {
            addCriterion("pay_safety <", value, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyLessThanOrEqualTo(Float value) {
            addCriterion("pay_safety <=", value, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyIn(List<Float> values) {
            addCriterion("pay_safety in", values, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyNotIn(List<Float> values) {
            addCriterion("pay_safety not in", values, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyBetween(Float value1, Float value2) {
            addCriterion("pay_safety between", value1, value2, "paySafety");
            return (Criteria) this;
        }

        public Criteria andPaySafetyNotBetween(Float value1, Float value2) {
            addCriterion("pay_safety not between", value1, value2, "paySafety");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_pay
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 17 21:12:54 AEDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_pay
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}