package com.ssm.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TbPrizePunishExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public TbPrizePunishExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPpTitleIsNull() {
            addCriterion("pp_title is null");
            return (Criteria) this;
        }

        public Criteria andPpTitleIsNotNull() {
            addCriterion("pp_title is not null");
            return (Criteria) this;
        }

        public Criteria andPpTitleEqualTo(String value) {
            addCriterion("pp_title =", value, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleNotEqualTo(String value) {
            addCriterion("pp_title <>", value, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleGreaterThan(String value) {
            addCriterion("pp_title >", value, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleGreaterThanOrEqualTo(String value) {
            addCriterion("pp_title >=", value, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleLessThan(String value) {
            addCriterion("pp_title <", value, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleLessThanOrEqualTo(String value) {
            addCriterion("pp_title <=", value, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleLike(String value) {
            addCriterion("pp_title like", value, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleNotLike(String value) {
            addCriterion("pp_title not like", value, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleIn(List<String> values) {
            addCriterion("pp_title in", values, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleNotIn(List<String> values) {
            addCriterion("pp_title not in", values, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleBetween(String value1, String value2) {
            addCriterion("pp_title between", value1, value2, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTitleNotBetween(String value1, String value2) {
            addCriterion("pp_title not between", value1, value2, "ppTitle");
            return (Criteria) this;
        }

        public Criteria andPpTypeIsNull() {
            addCriterion("pp_type is null");
            return (Criteria) this;
        }

        public Criteria andPpTypeIsNotNull() {
            addCriterion("pp_type is not null");
            return (Criteria) this;
        }

        public Criteria andPpTypeEqualTo(String value) {
            addCriterion("pp_type =", value, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeNotEqualTo(String value) {
            addCriterion("pp_type <>", value, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeGreaterThan(String value) {
            addCriterion("pp_type >", value, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("pp_type >=", value, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeLessThan(String value) {
            addCriterion("pp_type <", value, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeLessThanOrEqualTo(String value) {
            addCriterion("pp_type <=", value, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeLike(String value) {
            addCriterion("pp_type like", value, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeNotLike(String value) {
            addCriterion("pp_type not like", value, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeIn(List<String> values) {
            addCriterion("pp_type in", values, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeNotIn(List<String> values) {
            addCriterion("pp_type not in", values, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeBetween(String value1, String value2) {
            addCriterion("pp_type between", value1, value2, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpTypeNotBetween(String value1, String value2) {
            addCriterion("pp_type not between", value1, value2, "ppType");
            return (Criteria) this;
        }

        public Criteria andPpMoneyIsNull() {
            addCriterion("pp_money is null");
            return (Criteria) this;
        }

        public Criteria andPpMoneyIsNotNull() {
            addCriterion("pp_money is not null");
            return (Criteria) this;
        }

        public Criteria andPpMoneyEqualTo(Double value) {
            addCriterion("pp_money =", value, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyNotEqualTo(Double value) {
            addCriterion("pp_money <>", value, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyGreaterThan(Double value) {
            addCriterion("pp_money >", value, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("pp_money >=", value, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyLessThan(Double value) {
            addCriterion("pp_money <", value, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyLessThanOrEqualTo(Double value) {
            addCriterion("pp_money <=", value, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyIn(List<Double> values) {
            addCriterion("pp_money in", values, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyNotIn(List<Double> values) {
            addCriterion("pp_money not in", values, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyBetween(Double value1, Double value2) {
            addCriterion("pp_money between", value1, value2, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpMoneyNotBetween(Double value1, Double value2) {
            addCriterion("pp_money not between", value1, value2, "ppMoney");
            return (Criteria) this;
        }

        public Criteria andPpTimeIsNull() {
            addCriterion("pp_time is null");
            return (Criteria) this;
        }

        public Criteria andPpTimeIsNotNull() {
            addCriterion("pp_time is not null");
            return (Criteria) this;
        }

        public Criteria andPpTimeEqualTo(Date value) {
            addCriterionForJDBCDate("pp_time =", value, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("pp_time <>", value, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("pp_time >", value, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pp_time >=", value, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeLessThan(Date value) {
            addCriterionForJDBCDate("pp_time <", value, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pp_time <=", value, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeIn(List<Date> values) {
            addCriterionForJDBCDate("pp_time in", values, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("pp_time not in", values, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pp_time between", value1, value2, "ppTime");
            return (Criteria) this;
        }

        public Criteria andPpTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pp_time not between", value1, value2, "ppTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_prize_punish
     *
     * @mbg.generated do_not_delete_during_merge Mon Dec 17 21:12:54 AEDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_prize_punish
     *
     * @mbg.generated Mon Dec 17 21:12:54 AEDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}